### ISSUE TITLE
Catchment geojson contains invalid geometry

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#12]
For the sugar creek release files in catchment_data.geojson, cat-66 contains an invalid geometry when read by Shapely:

```
       ID  area_sqkm    toID                                           geometry  valid
6  cat-66   2.205631  nex-45  MULTIPOLYGON (((-80.76158 35.21440, -80.76163 ...  False
```

This prevents the geometry from being used for intersection:
`shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipoly
gon.MultiPolygon object at 0x11774f550>`

**Comment by dblodgett-usgs** [comment]
hrmmm... ok. QGIS reads it fine. GDAL does too but st_is_valid is FALSE for the feature you point out. 

On it.

**Comment by dblodgett-usgs** [comment]
[sugar_creek_refactor.zip](https://github.com/dblodgett-usgs/hygeo/files/4635780/sugar_creek_refactor.zip)

Can you try this one?

**Comment by hellkite500** [comment]
That works now, geometry is valid and intersection doesn't throw exception.

**Comment by dblodgett-usgs** [comment]
Great. I added a call to `st_make_valid()` in the writer. I'll cut a release and add this to the assets there quick.
