### ISSUE TITLE
v0.5.0 release artifacts contain build path and html

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#22]
The zip files in the release artifacts for v0.5.0 contain the build path in the zip, i.e. `docs/build/default/*.json` as well as an `index.html`.  These are intended to be flat zips containing the just data `*.json` and `*.geojson`.

**Comment by dblodgett-usgs** [comment]
Artifacts have been updated so they are 1-folder deep and only contain json and geojson now.
