### ISSUE TITLE
GeoJSON output keys in lowercase

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#24]
Is there a specific reason upper case keys are used in the properties, i.e. `ID`?  Could these be made lowercase.  It isn't a huge deal, but a consistent key case makes parsing easier.

**Comment by dblodgett-usgs** [comment]
I typically use upper case for identifiers and lowercase for attributes to set things apart. I can drop that convention if it is helpful elsewhere.
