### ISSUE TITLE
refactor crosswalk local_id

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#27]
Somewhat related to #15, and maybe a way to address some of the concerns raised there, should the crosswalk simply key by `local_id` instead of the `local_id` being embedded?

Currently the crosswalk is a list of objects like
`[{"local_id":"cat-1","COMID":"9731278"},...]`

After working with this in a couple places, I think it makes sense to factor out the common `local_id` and simply key by that.  Then even if we end up in a 1:many scenario, or different crosswalk definitions for waterbodies than catchments, there is still a unique mapping.  Propose changing crosswalk to something like
```json
{
    "cat-1": {
            "COMID":"9731278",
            "site_no":"123456789",
            "other_ref":"point to something"
    },
    "cat-2": {
            "COMID":"00000000",
            "site_no":"987654321",
            "other_ref":"point to something"
    }
}
```

**Comment by dblodgett-usgs** [comment]
Also add "outlet comid" as "other ref".
