### ISSUE TITLE
More crosswalk updates

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#28]
This release updates the crosswalk file to container structured linkages to catchments (i.e. `cat-X: {...}` 

https://github.com/dblodgett-usgs/hygeo/releases/tag/v0.5.3

It would be useful to have similar cross walk references for flowpaths, i.e.

```json
    `fp-1`:
    {
        "COMID": ["0000000", "00000001"],
        "outlet_comid": 0000000
    }
```

Since flowpaths are a realization of the catchment, I imagine it is also possible to connect the flowpath the NHD segments it coincides with much like the catchment, and this might also be useful. 

This definitely repeats information since a flowpath is keyed to a `realized_catchment`, but having these explicitly in the crosswalk provides a convenient and semantically consistent way to reference `catchment realizations` to NHD features, especially in cases where a flowpath exists but an area realization doesn't.

**Comment by dblodgett-usgs** [comment]
This is easy for me to add -- you know that we are 1:1 `cat-` and `fp-` right now right?

In the future, I could totally see having separation in what's in the crosswalk for these and it will get more complicated. So happy too add the easy thing now with the expectation that it gets more complex in the future.
