### ISSUE TITLE
Inconsistent application of COMID keys in crosswalk

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#29]
An entity with multiple COMIDs looks like:
```json
"cat-X": {
    "COMID": ["000000", "11111111", "2222222"]
}
```
whereas one with only a single COMID is:
```json
"cat-Y": {
    "COMID": "3333333"
}
```
In this latter case, the COMID should be a singleton list to keep a consistent schema, i.e.
```json
"cat-Y": {
    "COMID": ["3333333"]
}
```

**Comment by dblodgett-usgs** [comment]
I wrote the JSON with auto_unbox = TRUE ... so you want auto_unbox = FALSE?
https://github.com/dblodgett-usgs/hygeo/blob/master/vignettes/sugar_creek_refactor.Rmd#L224

**Comment by hellkite500** [comment]
Don't need _everything_ unboxed, just the "COMID".  Not sure what it will do to things like `site_no` and `outlet_COMID` which really should be scalar values.

**Comment by hellkite500** [comment]
Bumping this, still not fixed in latest release.
