### ISSUE TITLE
Incorrect mapping of gage site_no when a COMID is split

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#30]
![image](https://user-images.githubusercontent.com/5186647/99691360-c6705b80-2a4e-11eb-9468-12eaeb6dfd90.png)

Looking at this small subset of the [coarse data](https://dblodgett-usgs.github.io/hygeo/build/coarse/index.html) you can see an NWIS site that appears to be at the outlet of `cat-67`.  In the crosswalk, however you see
```json
  "cat-67": {
    "COMID": "9731286.1",
    "outlet_COMID": 9731286
  }
```
This shows that the comid `9731286` was split, and indeed `cat-68` shows the rest of that comid:
```json
  "cat-68": {
    "COMID": "9731286.2",
    "site_no": "02146562",
    "outlet_COMID": 9731286
  }
```
I think this is an artifact of splitting at the gage to create the upstream catchment, but then the gage isn't logically mapped to that catchment.

**Comment by dblodgett-usgs** [comment]
Dang! That's a bug. Will take care of it quick now.

**Comment by hellkite500** [comment]
This happens in all three  of the upper gages seen in the picture, `cat-27` -> `cat-26`, and `cat-52` -> `cat-34` are similarly affected.
